### ISSUE TITLE
Add me pretty plz

### ISSUE THREAD

**Issue by bnvk** [erming/shout-roadmap#1]
I'd love to be included in this / follow this planning. It will get me tinkering on my theme again :)

**Comment by JocelynDelalande** [comment]
@bnvk hi you :)

What do you mean « include me », do you want some version to be named after you ? ;-)

**Comment by bnvk** [comment]
@JocelynDelalande hey there! I guess I don't know what this repo is about or the plans- I just saw @erming adding people to it, and I'd love to be a part of the conversations / roadmap planning :)

**Comment by JocelynDelalande** [comment]
@bnvk so just stay tuned :) (I don't think adding you as collaborator would help, just follow it)

From what I got from @erming  this repo is to discuss/write down roadmap/plans for shout future. Stay tuned :) (I don't think adding you to the collaborators will help you in anything at the moment).

And note taken to remind you about https://github.com/opensourcedesign/slick from times to times ;-) (btw, just providing a screenshot of the work-in-progress would be great !).

**Comment by astorije** [comment]
@bnvk at the moment we'll do with issues and PRs to update a big README on that repo. So feel free to brain dump in either of these and we'll add. I still need to create the initial README though... Will do ASAP.

And when it becomes too tedious to work with issues/PR/repo for a roadmap for shout, I suggest we create https://github.com/erming/shout-roadmap-roadmap to discuss how to refactor the roadmap :-)

**Comment by bnvk** [comment]
Lolz! Alrighty, points taken!

**Comment by astorije** [comment]
Empty README added, @bnvk, go nuts! Don't worry about structure for now, let's dump brains and we'll structure after that.
