### ISSUE TITLE
Build Shout on top of a stand-alone IRC library.

### ISSUE THREAD

**Issue by simonv3** [erming/shout-roadmap#2]
How easy would it be to extract IRC interactions from Shout and make them into a solid, well maintained node library? 

We could help with the restructuring of [node-irc](https://www.npmjs.com/package/irc) who are not really [active anymore](https://github.com/martynsmith/node-irc/issues/399) and think they need a major restructure, or we could extract the existing IRC stuff from Shout. 

I think this modularity would make it easier to maintain the entire project, and if we actually started contributing to a refactor of node-irc we'd get a lot of help from the community around that package. It would also take a lot of work and maintenance away from Shout team.

**Comment by astorije** [comment]
If I understand your ticket, Shout is currently heavily relying on https://www.npmjs.com/package/slate-irc at the moment. Having the right backend library to rely on is indeed key to success here, and we'll need to investigate closely on that.

**Comment by JocelynDelalande** [comment]
@simonv3 Something I don't understand: shout is already using  the *slate-irc* lib as @astorije said, were you aware of that? do you think node-irc is a better choice?

**Comment by simonv3** [comment]
@JocelynDelalande I wasn't! I don't know if node-irc is a better choice - there's a lot of talk on there that it's too bloated.

**Comment by astorije** [comment]
Well at least it seems a bit more mature with some recent activity... Let's put both in the roadmap and try to identify which is the best underlying library to consider.

**Comment by astorije** [comment]
Done: #9.

Let's close this issue maybe?

**Comment by JocelynDelalande** [comment]
yes, closing.
